name: Build and run tests

on:
  pull_request:
    types: [labeled]
    branches:
      - master

jobs:
  build_and_test:
    name: Build and run tests
    runs-on: macos-latest

    env:
        FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 60
        FASTLANE_XCODEBUILD_SETTINGS_RETRIES: 5
        
    steps:        
      - name: Fail if label is not present
        if: contains(github.event.pull_request.labels.*.name, 'run-tests') == false
        run: exit 1

      - name: Setup - Xcode
        run: sudo xcode-select -s '/Applications/Xcode_13.2.1.app/Contents/Developer'
        
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          xcodebuild -scheme "VoiNetwork-Package" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0' test